### ISSUE TITLE
Reuse the X-Offset of the .pet note card number to affect Z (height)

### ISSUE THREAD

**Issue by Aaack-Aardvark** [lickx/oscollar-dev#19]
On the current .pet config card there's a number that affect the front to back offset of the avatar's animation.  That could be controlled by the animation itself, a more useful way to use that number is to affect the Z axis instead, to change the height of the avatar when the animation is playing to adjust it to the height of the collar wearing avatar.

Re using that number saves also from the need to add a new parametre on the notecard.

**Comment by lickx** [comment]
Aaack and me solved this now in a better way than editing the .pet notecard; height adjustments for pet anims (and other anims prefixed with ~) can now be made in the pose menu. They will appear in the last page(s) of that dialog.
