### ISSUE TITLE
Poses positions aren't saved

### ISSUE THREAD

**Issue by Aaack-Aardvark** [lickx/oscollar-dev#22]
After setting up the Z position of each pose if you press Settings->Save it won't change the positions in the notecard.
It does print them (so for now I did the old copy paste to save the positions), but they won't appear in the settings notecard.

**Comment by lickx** [comment]
I can't repro this. After I do this my OFFSET= line in the saved notecard is exactly the same as the printed line. Maybe your OFFSET= line is corrupt from testing/devving?
It needs to have the format:
OFFSET=hovers~anim1,0.01,anim2,0.03,anim3,0.02,etc

**Comment by lickx** [comment]
OK this is all finished and working
