### ISSUE TITLE
[oc_remote_bookmarks] Remote bookmarks issues

### ISSUE THREAD

**Issue by Aaack-Aardvark** [lickx/oscollar-dev#66]
The remote uses it's separate bookmarks notecard, it may be convenient to get the collar and remote in sync?

Also if you save a place in the remote's bookmarks and then try to teleport a collar user it fails with a message "Teleport Failed. You don't have access to the region parcels" <-- note the absence of a final period in the message.

Finally,. the bookmarks saves in memory, that would wipe them when HG teleporting.

**Comment by lickx** [comment]
Not sure yet how to do syncing. I could make the Remote Add or Remove bookmark command, also command that on the collar channel. But syncing the card itself will be difficult..

2nd issue I will have to investigate. Might even be a coordinate thing clipping at 256,256 (not taking into account var regions)

3rd issue is going to be worked on. No distinction between memory and card anymore, with the option to save what's in memory to card just like settings.
